DROP TABLE TBL_PARKING CASCADE CONSTRAINTS;
DROP TABLE TBL_CAR CASCADE CONSTRAINTS;
DROP TABLE TBL_PARKING_LOT CASCADE CONSTRAINTS;

CREATE TABLE TBL_CAR(
CAR_NUMBER CHAR(10) PRIMARY KEY,
CAR_NAME VARCHAR2(15),
OWNER_NAME VARCHAR2(20)
);

CREATE TABLE TBL_PARKING_LOT(
LOCATION CHAR(4) PRIMARY KEY,
HOURLY_PARKING_FEE NUMBER(10)
);

CREATE TABLE TBL_PARKING(
CAR_NUMBER CHAR(10),
LOCATION CHAR(4),
ENTRANCE_TIME VARCHAR2(6),
DEPARTURE_TIME VARCHAR2(6),

CONSTRAINT PK_CONST PRIMARY KEY (CAR_NUMBER, LOCATION),
CONSTRAINT FK1 FOREIGN KEY (CAR_NUMBER)
	REFERENCES TBL_CAR(CAR_NUMBER),
CONSTRAINT FK2 FOREIGN KEY (LOCATION)
	REFERENCES TBL_PARKING_LOT(LOCATION)
);

INSERT INTO TBL_CAR VALUES('11가1111','그랜저','박선수');
INSERT INTO TBL_CAR VALUES('22가1111','K3','백선수');
INSERT INTO TBL_CAR VALUES('33가1111','셀토스','채선수');
INSERT INTO TBL_CAR VALUES('44가1111','SM5','임선수');
INSERT INTO TBL_CAR VALUES('55가1111','티볼리','한선수');
 
INSERT INTO TBL_PARKING_LOT VALUES('A001',1000);
INSERT INTO TBL_PARKING_LOT VALUES('A002',1000);
INSERT INTO TBL_PARKING_LOT VALUES('A003',1000);
INSERT INTO TBL_PARKING_LOT VALUES('A004',1000);
INSERT INTO TBL_PARKING_LOT VALUES('A005',1000);

--제일 마지막에 입력
INSERT INTO TBL_PARKING(CAR_NUMBER,LOCATION, ENTRANCE_TIME) 
VALUES('11가1111', 'A001', '11:22');

SELECT * FROM TBL_CAR C JOIN TBL_PARKING P 
ON C.CAR_NUMBER = P.CAR_NUMBER 
WHERE C.CAR_NUMBER='11가1111';